# Generated by Django 4.1.7 on 2023-04-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("nombre", models.CharField(max_length=256)),
                ("descripcion", models.TextField()),
                (
                    "numero",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "tema",
                    models.PositiveIntegerField(
                        help_text="Uno de los grandes temas del curso."
                    ),
                ),
            ],
        ),
    ]
