# Generated by Django 5.0 on 2024-02-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="career",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.career"
            ),
        ),
    ]
