# Generated by Django 4.2.10 on 2024-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.TextField()),
                ("output", models.CharField(max_length=100)),
            ],
        ),
    ]
