# Generated by Django 4.2.10 on 2024-02-14 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_rename_name_snippet_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Snippet",
        ),
    ]
